Update buildspec.yml

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -70,10 +70,13 @@ phases:
     - quality_status=$(jq -r '.projectStatus.status' sonarqube_scanreport.json)
     - |
       if [ $quality_status = "FAILED" ]; then
-        echo "SonarQube analysis failed"
+        echo "SonarQube analysis failed with status: $quality_status"
         exit 1
+      elif [ $quality_status = "PASSED" ]; then
+        echo "SonarQube analysis passed with status: $quality_status"
       else
-        echo "SonarQube analysis passed"
+        echo "Invalid status: $quality_status"
+        exit 1
       fi
 artifacts:
   files: 'my-app-1.0-SNAPSHOT.jar'
