updated post_build section that removes the Lambda function

diff --git a/buildspec.yml b/buildspec.yml
--- a/buildspec.yml
+++ b/buildspec.yml
@@ -62,6 +62,18 @@ phases:
   #         echo "in quality_status  unexpected condition"
   #         exit 1;
   #       fi
+  post_build:
+  commands:
+    - SCAN_RESULT=$(curl -sS -o sonarqube_scan_report.json -u $SonarQube_Access_Token $SonarQube_URL/api/issues/search?createdAfter=2020-10-21&componentKeys=devsecops&severities=CRITICAL,BLOCKER&languages=php&types=VULNERABILITY&onComponentOnly=true)
+    - quality_status=$(jq -r '.projectStatus.status' sonarqube_scan_rport.json)
+    - |
+      if [ $quality_status = "ERROR" ] || [ $quality_status = "WARN" ]; then
+        echo "SonarQube analysis failed with status: $quality_status"
+        exit 1
+      else
+        echo "SonarQube analysis passed with status: $quality_status"
+      fi
+
 artifacts:
   files: 'my-app-1.0-SNAPSHOT.jar'
   base-directory: 'target'
